apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: qos-scheduler # scheduler name
  plugins:
    queueSort:
      enabled:
      - name: QOSSort
      disabled:
      - name: "*"