# preprocessing_binary_api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessingbinaryapi
spec:
  replicas: 1 # Initial number of deployed replicas
  selector:
    matchLabels:
      app: preprocessingbinaryapi
  template:
    metadata:
      labels:
        app-group.scheduling.sigs.k8s.io: ids3
        app: preprocessingbinaryapi
        workload: preprocessingbinaryapi
    spec:
      schedulerName: diktyo-priority-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - preprocessingbinaryapi
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: preprocessingbinaryapi
        image: gitlab.ilabt.imec.be:4567/josperei/multi-stage-ids-for-kubernetes/preprocessing_binary_slim:latest
        imagePullPolicy: IfNotPresent # To avoid pulling the image if already present
        ports:
        - containerPort: 8005
        env: # define env variables
        - name: MODEL_MULTI_CLASS_HOST
          value: "http://preprocessingmulticlassapi:8006"
        - name: MODEL_TAU_B
          value: "-0.0002196942507948895"
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_PORT
          value: "8005"
        - name: UVICORN_LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
--- # preprocessing_binary_api service
apiVersion: v1
kind: Service
metadata:
  name: preprocessingbinaryapi
spec:
  type: ClusterIP
  selector:
    app: preprocessingbinaryapi
  ports:
  - name: grpc
    port: 8005
    targetPort: 8005
--- # preprocessing_multi_class_api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessingmulticlassapi
spec:
  replicas: 1 # Initial number of deployed replicas
  selector:
    matchLabels:
      app: preprocessingmulticlassapi
  template:
    metadata:
      labels:
        app-group.scheduling.sigs.k8s.io: ids3
        app: preprocessingmulticlassapi
        workload: preprocessingmulticlassapi
    spec:
      schedulerName: diktyo-priority-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - preprocessingmulticlassapi
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: preprocessingmulticlassapi
        image: gitlab.ilabt.imec.be:4567/josperei/multi-stage-ids-for-kubernetes/preprocessing_multiclass_slim:latest
        imagePullPolicy: IfNotPresent # To avoid pulling the image if already present
        ports:
        - containerPort: 8006
        env: # define env variables
        - name: MODEL_ZERO_DAY_HOST
          value: "http://zerodayapi:8003"
        - name: MODEL_TAU_M
          value: "0.98"
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_PORT
          value: "8006"
        - name: UVICORN_LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 400m
            memory: 192Mi
          limits:
            cpu: 800m
            memory: 384Mi
--- # preprocessing_multi_class_api service
apiVersion: v1
kind: Service
metadata:
  name: preprocessingmulticlassapi
spec:
  type: ClusterIP
  selector:
    app: preprocessingmulticlassapi
  ports:
  - name: grpc
    port: 8006
    targetPort: 8006
--- # zerodayapi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerodayapi
spec:
  replicas: 1 # Initial number of deployed replicas
  selector:
    matchLabels:
      app: zerodayapi
  template:
    metadata:
      labels:
        app-group.scheduling.sigs.k8s.io: ids3
        app: zerodayapi
        workload: zerodayapi
    spec:
      schedulerName: diktyo-priority-scheduler
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - preprocessingmulticlassapi
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: zerodayapi
        image: gitlab.ilabt.imec.be:4567/josperei/multi-stage-ids-for-kubernetes/zero_day_api_slim:latest
        imagePullPolicy: IfNotPresent # To avoid pulling the image if already present
        ports:
        - containerPort: 8003
        env: # define env variables
        - name: MODEL_TAU_U
          value: "0.0040588613744241275"
        - name: UVICORN_HOST
          value: "0.0.0.0"
        - name: UVICORN_PORT
          value: "8003"
        - name: UVICORN_LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
--- # zerodayapi service
apiVersion: v1
kind: Service
metadata:
  name: zerodayapi
spec:
  type: ClusterIP
  selector:
    app: zerodayapi
  ports:
  - name: grpc
    port: 8003
    targetPort: 8003
---